services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - crawler
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - crawler
    volumes:
      - cache:/data

networks:
  crawler:


volumes:
  rabbitmq_data:
  cache:
